apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpha
  template:
    metadata:
      labels:
        app: alpha
      annotations:
        # https://www.consul.io/docs/platf orm/k8s/run.html#annotations
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service-upstreams': 'beta-service:50100,charlie-service:50200'
    spec:
      containers:
        - name: alpha
          image: leofvo/alpha:1.0.0
          ports:
            - containerPort: 8000
          env:
            - name: BETA_URL
              value: 'http://localhost:50100'
            - name: CHARLIE_URL
              value: 'http://localhost:50200'
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              memory: '256Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '200m'
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-service
spec:
  selector:
    app: alpha
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
