apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beta
  template:
    metadata:
      labels:
        app: beta
      annotations:
        instrumentation.opentelemetry.io/inject-python: 'observability/python-instrumentation'
    spec:
      containers:
        - name: beta
          image: leofvo/beta:1.0.0
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              memory: '256Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '200m'
---
apiVersion: v1
kind: Service
metadata:
  name: beta-service
spec:
  selector:
    app: beta
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
