apiVersion: apps/v1
kind: Deployment
metadata:
  name: charlie-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: charlie
  template:
    metadata:
      labels:
        app: charlie
      annotations:
        # https://www.consul.io/docs/platf orm/k8s/run.html#annotations
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service-upstreams': '50010'
    spec:
      containers:
        - name: charlie
          image: leofvo/charlie:1.0.0
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              memory: '256Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '200m'
---
apiVersion: v1
kind: Service
metadata:
  name: charlie-service
spec:
  selector:
    app: charlie
  ports:
    - protocol: TCP
      port: 50200
      targetPort: 8000
