apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:latest
    options:
      log-level: debug
      prometheus:
        server-url: 'http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090'
        query:
          support-spanmetrics-connector: true
          normalize-calls: true
          normalize-duration: true
    metricsStorage:
      type: prometheus
  storage:
    type: memory
    options:
      memory:
        max-traces: 100000
  ingress:
    enabled: false
  ui:
    options:
      dependencies:
        menuEnabled: true
